---
title: "A1_BSGS"
author: "Ni Zhang"
date: "5/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## AIM 1: Testing the existing classifier - Southern Denmark

### Weights obtained from supplementary Data 13

```{r}
library("GEOquery")
library(readxl)
```

```{r}
# Access the GEO Series Data
gse <- getGEO("GSE56105", GSEMatrix = TRUE)
```

```{r}
gse_data = gse$GSE56105_series_matrix.txt.gz@phenoData@data
gse_data
```

```{r}
write.table(gse_data, file = "data3.csv",row.names=FALSE,col.names=TRUE,sep=",")
```


```{r}
s13 = read.csv('GSE56105Supple13.csv')
s13_p = read_excel('41467_2021_25583_MOESM9_ESM.xlsx', sheet = 2)
response = read.csv("data3.csv")
```


```{r}
# add intercept to s13
intercept = c(rep(1,614))
new_s13 = cbind(intercept,s13)
```

```{r}
# dot product
new_s13 =  as.matrix(new_s13)
new_s13[is.na(new_s13)] = 0
res1_1 = new_s13 %*% as.matrix(s13_p[,2]) 
res1_1 <- 1/(1+exp(-res1_1))
```

```{r}
# For x greater than cutoff, assign it to 'MZ'
# For x smaller than cutoff, assign it to 'DZ'
# 0.662048479785103 is calculated from line 106 using package "caret"
zygosity.true = response$zygosity
zygosity.predicted = apply(res1_1, 2, function(x) ifelse(x >= 0.662048479785103, "MZ", "DZ"))
```


```{r}
# Making '0' to 'DZ' in zygosity.changed
predicted_vs_true2 = data.frame(zygosity.predicted, zygosity.true, res1_1)
predicted_vs_true2[,4] = predicted_vs_true2[,2]
predicted_vs_true2[,4][predicted_vs_true2[,4] == '0'] = 'DZ'
colnames(predicted_vs_true2) = c('Estimate','zygosity.true','prob', 'zygosity.changed')
predicted_vs_true2[,4] = droplevels(predicted_vs_true2[,4])
predicted_vs_true2
```

```{r}
# confusion matrix ( 2 * 3)
confusion.matrix = xtabs(~ Estimate + zygosity.true, predicted_vs_true2)
confusion.matrix
```

```{r}
library(pROC)
library(ROCR)
```

```{r}
predicted_vs_true3 = apply(predicted_vs_true2[,1:2],2, function(x) ifelse(x == 'MZ', 1, 0))
predicted_vs_true3_1 = apply(predicted_vs_true2[,3:4],2, function(x) ifelse(x == 'MZ', 1, 0))
predicted_vs_true3 = cbind(predicted_vs_true3[,1],predicted_vs_true3_1[,2], prob = predicted_vs_true2[,3])
predicted_vs_true3
```

```{r}
# ROC curve
pred <- prediction(predicted_vs_true3[,3], predicted_vs_true3[,2])
perf <- performance(pred,"tpr","fpr")
perf
plot(perf,colorize=TRUE)
```

```{r}
# Model performance
library(caret)
roc.p = roc(predicted_vs_true3[,2], predicted_vs_true3[,3])
cutoff = roc.p$thresholds[which.max(roc.p$sensitivities+roc.p$specificities)]
pred_b = as.integer(predicted_vs_true3[,3]>cutoff)
cft = table(pred_b, predicted_vs_true3[,2])
cm = confusionMatrix(cft, positive = '1', mode = 'everything')
paste0('cutoff: ', cutoff)
print(roc.p$auc)
print(cm)
```

### Weights obtained from supplementary Data 14

```{r}
# s14 
s14 = read.csv('GSE56105Supple14.csv')
s14_p = read_excel('41467_2021_25583_MOESM9_ESM.xlsx', sheet = 3)
new_s14 = cbind(intercept,s14)
new_s14 =  as.matrix(new_s14)
new_s14[is.na(new_s14)] = 0
res2_1 = new_s14 %*% as.matrix(s14_p[,2])
res2_1 <- 1/(1+exp(-res2_1))
```


```{r}
# For x greater than cutoff, assign it to 'MZ'
# For x smaller than cutoff, assign it to 'DZ'
zygosity.predicted.s14 = apply(res2_1, 2, function(x) ifelse(x >= 0.543929063793188, "MZ", "DZ"))
```

```{r}
# Making '0' to 'DZ' in zygosity.changed
predicted_vs_true2.s14 = data.frame(zygosity.predicted.s14, zygosity.true, res2_1)
predicted_vs_true2.s14[,4] = predicted_vs_true2.s14[,2]
predicted_vs_true2.s14[,4][predicted_vs_true2.s14[,4] == '0'] = 'DZ'
colnames(predicted_vs_true2.s14) = c('Estimate','zygosity.true','prob', 'zygosity.changed')
predicted_vs_true2.s14[,4] = droplevels(predicted_vs_true2.s14[,4])
predicted_vs_true2.s14
```

```{r}
# confusion matrix ( 2 * 3)
confusion.matrix2 = xtabs(~ Estimate + zygosity.true, predicted_vs_true2.s14)
confusion.matrix2
```


```{r}
predicted_vs_true3.s14 = apply(predicted_vs_true2.s14[,1:2],2, function(x) ifelse(x == 'MZ', 1, 0))
predicted_vs_true3_1.s14 = apply(predicted_vs_true2.s14[,3:4],2, function(x) ifelse(x == 'MZ', 1, 0))
predicted_vs_true3.s14 = cbind(predicted_vs_true3.s14[,1],predicted_vs_true3_1.s14[,2], prob = predicted_vs_true2.s14[,3])
```

```{r}
# ROC curve
pred.s14 <- prediction(predicted_vs_true3.s14[,3], predicted_vs_true3.s14[,2])
perf.s14 <- performance(pred.s14,"tpr","fpr")
perf.s14
plot(perf.s14,colorize=TRUE)
```

```{r}
# Model performance
library(caret)
roc.p.s14 = roc(predicted_vs_true3.s14[,2], predicted_vs_true3.s14[,3])
cutoff.s14 = roc.p.s14$thresholds[which.max(roc.p.s14$sensitivities+roc.p.s14$specificities)]
pred_b.s14 = as.integer(predicted_vs_true3.s14[,3]>cutoff.s14)
cft.s14 = table(pred_b.s14, predicted_vs_true3.s14[,2])
cm.s14 = confusionMatrix(cft.s14, positive = '1', mode = 'everything')
paste0('cutoff: ', cutoff.s14)
print(roc.p.s14$auc)
print(cm.s14)
```




