---
title: "data_833"
author: "Ni Zhang"
date: "8/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ERisk_833 = read.csv('ERisk_833.csv')
ERisk_label = read.csv('ERisk_label.csv')
```

```{r}
ERisk_label$zygostiy[ERisk_label$zygostiy == 'MZ'] <- 1
ERisk_label$zygostiy[ERisk_label$zygostiy == 'DZ'] <- 0
ERisk_label$zygostiy = as.integer(ERisk_label$zygostiy)
label = ERisk_label[,2]
ERisk_data = cbind(label,ERisk_833)
write.table(ERisk_data, file = "ERisk_data",row.names=FALSE,col.names=TRUE,sep=",")
```

```{r}
BSGS_833 = read.csv('BSGS_833.csv')
BSGS_label = read.csv('BSGS_label.csv')
```

```{r}
label_BSGS = BSGS_label[,5]
BSGS_data = cbind(label_BSGS,BSGS_833)
write.table(BSGS_data, file = "BSGS_data.csv",row.names=FALSE,col.names=TRUE,sep=",")
```

```{r}
DENMARK_833 = read.csv('DENMARK_833.csv')
DENMARK_label = read.csv('DENMARK_label.csv')
```

```{r}
label_DENMARK = DENMARK_label[,5]
DENMARK_data = cbind(label_DENMARK,DENMARK_833)
write.table(DENMARK_data, file = "DENMARK_data.csv",row.names=FALSE,col.names=TRUE,sep=",")
```

